### ISSUE TITLE
Minor documentation errors

### ISSUE THREAD

**Issue by mgdde** [Befaco/muxlicer#1]
Hi!

The description references under 4) the library "Rotary Encoder" which I guess is a copy-and-paste error from burst. It shoud say "ClickEncoder". It also should reference TimerOne as another prerequisite.

Likewise under 6) BURST.ino is referenced when it should say muxlicer.ino

Kind regards,
Michael

**Comment by xustafu** [comment]
Thansk a bunch for the heads up!!
Readme edited.
